name: StartupBusiness
favicon: null
layout_spectrum: 0.09989
typography_spectrum: 0.54355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#30302e'
    - '#677484'
    - '#abafb2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
